package example.bean;

import java.util.Date;

import example.utils.RedisClient;
import redis.clients.jedis.Jedis;
import split.policy.IPolicy;

public class TbReceiverAddress extends IPolicy<Integer> {
	
	private static final String KEY_INDEX = "receiver_address_key";
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.user_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.receiver_name
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.mobile
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.tel_code
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private String telCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.tel
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.tel_ext_number
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private String telExtNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.province_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.province_name
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.city_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.city_name
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.county_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private Integer countyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.county_name
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private String countyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.address
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.post_code
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.is_default
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private Integer isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.last_update_time
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.last_update_user_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private Integer lastUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.create_time
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.create_user_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_address.email
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.id
     *
     * @return the value of tb_receiver_address.id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.id
     *
     * @param id the value for tb_receiver_address.id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.user_id
     *
     * @return the value of tb_receiver_address.user_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.user_id
     *
     * @param userId the value for tb_receiver_address.user_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.receiver_name
     *
     * @return the value of tb_receiver_address.receiver_name
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.receiver_name
     *
     * @param receiverName the value for tb_receiver_address.receiver_name
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.mobile
     *
     * @return the value of tb_receiver_address.mobile
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.mobile
     *
     * @param mobile the value for tb_receiver_address.mobile
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.tel_code
     *
     * @return the value of tb_receiver_address.tel_code
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public String getTelCode() {
        return telCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.tel_code
     *
     * @param telCode the value for tb_receiver_address.tel_code
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setTelCode(String telCode) {
        this.telCode = telCode == null ? null : telCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.tel
     *
     * @return the value of tb_receiver_address.tel
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.tel
     *
     * @param tel the value for tb_receiver_address.tel
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.tel_ext_number
     *
     * @return the value of tb_receiver_address.tel_ext_number
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public String getTelExtNumber() {
        return telExtNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.tel_ext_number
     *
     * @param telExtNumber the value for tb_receiver_address.tel_ext_number
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setTelExtNumber(String telExtNumber) {
        this.telExtNumber = telExtNumber == null ? null : telExtNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.province_id
     *
     * @return the value of tb_receiver_address.province_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.province_id
     *
     * @param provinceId the value for tb_receiver_address.province_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.province_name
     *
     * @return the value of tb_receiver_address.province_name
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.province_name
     *
     * @param provinceName the value for tb_receiver_address.province_name
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.city_id
     *
     * @return the value of tb_receiver_address.city_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.city_id
     *
     * @param cityId the value for tb_receiver_address.city_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.city_name
     *
     * @return the value of tb_receiver_address.city_name
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.city_name
     *
     * @param cityName the value for tb_receiver_address.city_name
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.county_id
     *
     * @return the value of tb_receiver_address.county_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public Integer getCountyId() {
        return countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.county_id
     *
     * @param countyId the value for tb_receiver_address.county_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setCountyId(Integer countyId) {
        this.countyId = countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.county_name
     *
     * @return the value of tb_receiver_address.county_name
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public String getCountyName() {
        return countyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.county_name
     *
     * @param countyName the value for tb_receiver_address.county_name
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setCountyName(String countyName) {
        this.countyName = countyName == null ? null : countyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.address
     *
     * @return the value of tb_receiver_address.address
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.address
     *
     * @param address the value for tb_receiver_address.address
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.post_code
     *
     * @return the value of tb_receiver_address.post_code
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.post_code
     *
     * @param postCode the value for tb_receiver_address.post_code
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.is_default
     *
     * @return the value of tb_receiver_address.is_default
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.is_default
     *
     * @param isDefault the value for tb_receiver_address.is_default
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.last_update_time
     *
     * @return the value of tb_receiver_address.last_update_time
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.last_update_time
     *
     * @param lastUpdateTime the value for tb_receiver_address.last_update_time
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.last_update_user_id
     *
     * @return the value of tb_receiver_address.last_update_user_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public Integer getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.last_update_user_id
     *
     * @param lastUpdateUserId the value for tb_receiver_address.last_update_user_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setLastUpdateUserId(Integer lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.create_time
     *
     * @return the value of tb_receiver_address.create_time
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.create_time
     *
     * @param createTime the value for tb_receiver_address.create_time
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.create_user_id
     *
     * @return the value of tb_receiver_address.create_user_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.create_user_id
     *
     * @param createUserId the value for tb_receiver_address.create_user_id
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_address.email
     *
     * @return the value of tb_receiver_address.email
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_address.email
     *
     * @param email the value for tb_receiver_address.email
     *
     * @mbggenerated Thu May 22 18:36:19 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
    
    public static void main(String[] args) {
    	TbReceiverAddress receiverAddress = new TbReceiverAddress();
    	receiverAddress.createKey();
	}

	@Override
	public Integer createKey() {
		Jedis jedis = null;
		try{
			jedis = RedisClient.getJedis();
			Long longKey = jedis.incr(KEY_INDEX);
			return longKey.intValue();
		}catch(Exception e){
			e.printStackTrace();
		}finally{
			RedisClient.returnJedis(jedis);
		}
		return 0;
	}

	@Override
	public String getClusterId() {
		//does't need cluster id now
		return null;
	}

	@Override
	public String getDBId() {
		if(this.id!=null && this.id!=0){
			int intMod = this.id%2;
			return "db"+intMod;
		}
		return null;
	}

	@Override
	public String getTableId() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String[] getDBIdsByClusterId(String clusterId) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String[] getTableIdsByDbId(String id) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String[] getAllClusterId() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String[] getAllDBId() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String[] getAllTableId() {
		// TODO Auto-generated method stub
		return null;
	}
}